---
functional:
  - Возможность выбора соревнования по типу, сложности и названию задания
  - Возможность выбора соперника - бот, случайный пользователь, определённый
    пользователь
  - Система рейтинга пользователей
  - Возможность выбора языка программирования при решении задачи
  - Наличие внутреннего чата для пользователей
non-fuctional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован
    для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров
  - Обрабатывать одновременно не менее 1000 пользователей
implicit:
  - Авторизация пользователя по почте и паролю, либо по аккаунту GitHUB или
    Discord
  - Градация начисления баллов в зависимости от сложности игры
  - Счётчик игр для каждого пользователя