---
functional:
  - Пользователь должен иметь возможность регистрации, авторизации и аутентификации на сайте
  - Пользователь должен иметь возможность авторизации по адресу почты
  - Пользователь должен иметь возможность авторизации с помощью профиля GitHub
  - Пользователь должен иметь возможность авторизации с помощью профиля Discord
  - Неавторизованный пользователь должен иметь возможность начать игру без регистрации
  - На платформе должен быть реализован личный профиль пользователя
  - Наличие системы рейтинга пользователей
  - Возможность выбора соревнования по типу, сложности и названию задания
  - Возможность выбора соперника - бот, случайный пользователь, определённый пользователь
  - Возможность выбора и изменения языка программирования при решении задачи
  - Наличие внутреннего чата для пользователей
non-fuctional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать персональные данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями популярных браузеров
  - Обрабатывать одновременно не менее 1000 пользователей
implicit:
  - Пользователь должен иметь возможность просматривать свой рейтинг и профиль
  - Пользователь должен иметь возможность просматривать профили и рейтинги других игроков
  - Пользователь должен иметь возможность смотреть за матчем других игроков
  - Пользователь должен иметь возможность вызвать другого игрока на матч
  - Пользователь должен иметь возможность смены темы во время матча на "светлая" или "темная"
  - Пользователь должен иметь возможность возврата на главную страницу кнопкой
  - Система должна иметь средства для предотвращения читерства